### ISSUE TITLE
Create a template for articles

### ISSUE THREAD

**Issue by Barbapapazes** [unjs/website#136]
### Environment

/

### Reproduction

/

### Describe the bug

The idea is to have a template with a check list in order to check things before they are published.

```[tasklist]
### Tasks
- [ ] Reviewed by package creator / maintainer
- [ ] Use `we` not `you`
- [ ] Structure template with an introduction and a conclusion
```

**Comment by pi0** [comment]
Nice idea overall and i love consistency across!

BTW some small things like narrative i think should be up to the writer. Something like "You can run the server locally" seems totally fine to me. We can just prepare some recommendation guidelines (just like the lint rules we have across unjs that are only advice to use)

**Comment by Barbapapazes** [comment]
Yes, use the template as a recommandation is totally fine for me! This remind me that "consistency" inside a single article is important! I often see myself starting with `we`, then using `you` and finishing by `we` 😅
